export const INITIATED = 'app/home/INITIATED';
export const TASK_LIST_FETCH_REQUEST = 'app/home/TASK_LIST_FETCH_REQUEST';
export const TASK_LIST_FETCH_FAIL = 'app/home/TASK_LIST_FETCH_FAIL';
export const TASK_LIST_FETCH_SUCCEEDED = 'app/home/TASK_LIST_FETCH_SUCCEEDED';
